[package]
name = "bonomen"
version = "0.1.0"
authors = ["ner0x652 <cornel.punga@gmail.com>"]

[dependencies]
strsim = "0.5.2"
clap   = "2.19.2"
log    = "*"
psutil = { git = "https://github.com/ner0x652/rust-psutil" }

[profile.dev]
opt-level = 3

[profile.release]
debug-assertions = true